apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: nodeproject-dev
type: Opaque
data:
  # Consider using Kubernetes Secrets Management or Environment Variables for improved security.
  DB_HOST: bm9kZXBsYXRmb3JtZXltdXNlcy5teXNxbC5kYXNlYm9vaw==
  DB_USER: bXlzcWw=
  DB_PASSWORD: UmVkQDY4NjY3Mw==
  DB_NAME: c29ja2E=