apiVersion: v1
kind: Namespace
metadata:
  name: nodeproject-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodeproject-dev
  name: node-app-deployment
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: pratheeshsatheeshkumar/nodeapp:87700b0b5b263994f9e68c5cf5f7d245bc5fccc6
        imagePullPolicy: Always
        name: node-app
        ports:
        - containerPort: 2000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"      
---
apiVersion: v1
kind: Service
metadata:
  namespace: nodeproject-dev
  name: node-app-service
spec:
  ports:
    - port: 80
      targetPort: 2000
      protocol: TCP
  type: NodePort
  selector:
    app: node-app
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nodeproject-dev
  name: node-app-ingress
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-app-service
                port:
                  number: 80
