name: CI Pipeline

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_SSL_CA: ./certs/DigiCertGlobalRootG2.crt.pem
      run: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/nodeapp:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/nodeapp:latest

    - name: Update Deployment YAML
      run: |
        sed -i 's|image: pratheeshsatheeshkumar/nodeapp:.*|image: pratheeshsatheeshkumar/nodeapp:${{ github.sha }}|' ./manifests/deployment.yaml

    - name: Commit and Push Deployment YAML
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin feature
        git add ./manifests/deployment.yaml
        git commit -m "Update deployment image tag to ${{ github.sha }}"
        git push origin feature

